<Workspace Version="1.3.3.4111" X="-114.5926674726" Y="-282.084715399434" zoom="1.05429821501133" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8ec838a1-f42c-45dd-b081-95f8c0880cdd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="646.065510458078" y="517.896996477394" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import System
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#Source document with correct families
doc_source = app.OpenDocumentFile(IN[0])

#Families
elements_source = []
elements_target = []

#Names of families
elements_source_name = []
elements_target_name = []
elements_source_name_filtered = []

result = []

#Ensure loaded families can overwrite existing families
class FamilyOption(IFamilyLoadOptions):
    def OnFamilyFound(self, familyInUse, overwriteParameterValues):
        overwriteParameterValues = True
        return True

    def OnSharedFamilyFound(self, sharedFamily, familyInUse, source, overwriteParameterValues):
        source = FamilySource.Family
        overwriteParameterValues = True
        return True

try:
	errorReport = None
	
	#Collecting families from both files
	elements_source = FilteredElementCollector(doc_source).OfClass(Family).ToElements()
	elements_target = FilteredElementCollector(doc).OfClass(Family).ToElements()
		
	#Adding families to filtered list if families have same names
	for i in elements_source:
		elements_source_name.append(Element.Name.GetValue(i).ToString())
	for i in elements_target:
		elements_target_name.append(Element.Name.GetValue(i).ToString())
	for i in elements_source_name:
		for j in elements_target_name:
			if i == j:
				elements_source_name_filtered.append(i)
	
	#Closing all transactions
	TransactionManager.Instance.ForceCloseTransaction()
	
	#Replacing families by opening and loading them
	for i in elements_source:
		if Element.Name.GetValue(i).ToString() in elements_source_name_filtered:
			if i.IsEditable:
				editing = doc_source.EditFamily(i)
				editing.LoadFamily(doc, FamilyOption())
				editing.Close(False)
				result.append("Family " + Element.Name.GetValue(i).ToString() + " was replaced")
	
except:
	#If error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()
	
#Assign your output to the OUT variable
if errorReport == None:
	OUT = result
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Filename guid="2363ddf7-e205-43d0-8a03-ac66d2d6aa70" type="CoreNodeModels.Input.Filename" nickname="Document with correct families" x="165.49542798024" y="516.503951492614" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Q:\00_General\01_BIM Standards\01_Standards\Revit Template\GSA_Catalog_2019_190502.rte</System.String>
      <HintPath>Q:\00_General\01_BIM Standards\01_Standards\Revit Template\GSA_Catalog_2019_190502.rte</HintPath>
    </CoreNodeModels.Input.Filename>
    <CoreNodeModels.Watch guid="d33b055e-0aaf-4a22-8092-430ad137998e" type="CoreNodeModels.Watch" nickname="Result" x="862.895429577977" y="520.086950886308" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8ec838a1-f42c-45dd-b081-95f8c0880cdd" start_index="0" end="d33b055e-0aaf-4a22-8092-430ad137998e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2363ddf7-e205-43d0-8a03-ac66d2d6aa70" start_index="0" end="8ec838a1-f42c-45dd-b081-95f8c0880cdd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>