<Workspace Version="1.3.4.6666" X="-101.522168504238" Y="53.7467309249473" zoom="1.00693338659567" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Watch guid="8f08d78a-d6be-4a6f-8de9-aa645dd817de" type="CoreNodeModels.Watch" nickname="Result" x="820.546218294348" y="297.985660943566" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="59d085cb-d833-478a-b027-bb210520de93" type="PythonNodeModels.PythonNode" nickname="Python Script" x="641.798989379445" y="295.984384719941" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI.Selection import Selection
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import List
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument


family = doc.OwnerFamily


def FindVoids(elements):
	voids = [i for i in elements if not i.IsSolid]
	return voids


Options().ComputeReferences = True
Options().IncludeNonVisibleObjects = True


#  Get geometry primitives
prim_ext = FilteredElementCollector(doc).OfClass(Extrusion).ToElements()
prim_bln = FilteredElementCollector(doc).OfClass(Blend).ToElements()
prim_rev = FilteredElementCollector(doc).OfClass(Revolution).ToElements()
prim_swe = FilteredElementCollector(doc).OfClass(Sweep).ToElements()
prim_swb = FilteredElementCollector(doc).OfClass(SweptBlend).ToElements()

#  Find voids
voids = []
voids.extend(FindVoids(prim_ext))
voids.extend(FindVoids(prim_bln))
voids.extend(FindVoids(prim_rev))
voids.extend(FindVoids(prim_swe))
voids.extend(FindVoids(prim_swb))

#  Selection
ids = List[ElementId]()
for i in voids:
	ids.Add(i.Id)
sel = uidoc.Selection.SetElementIds(ids)

#  Output
if ids:
	OUT = str(len(ids)) + " voids selected."
else:
	OUT = "No voids are in the family."</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="3e1291a5-09e9-4d76-ba01-6b86feb7349c" type="CoreNodeModels.Input.BoolSelector" nickname="Restart" x="450.551650400908" y="295.855320432326" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="59d085cb-d833-478a-b027-bb210520de93" start_index="0" end="8f08d78a-d6be-4a6f-8de9-aa645dd817de" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3e1291a5-09e9-4d76-ba01-6b86feb7349c" start_index="0" end="59d085cb-d833-478a-b027-bb210520de93" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-5.41140937805176" eyeY="2.18570351600647" eyeZ="19.8241634368896" lookX="4.90884685516357" lookY="-5.3179178237915" lookZ="-23.726095199585" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>