<Workspace Version="1.3.4.6666" X="-213.4941259681" Y="-239.953673339022" zoom="0.983096703456761" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c95d741a-105e-4832-9740-9cbe583c9238" type="PythonNodeModels.PythonNode" nickname="Python Script" x="757.227596621497" y="342.613798310748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument


digits = int(IN[0])
parameter_name = IN[1]
parameter_2_name = IN[2]
bottom = IN[3]


generic = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_MechanicalEquipment).WhereElementIsNotElementType().ToElements()
openings = []
openings_round = []
for i in generic:
	family_parameter = i.LookupParameter("Family")
	family = family_parameter.AsValueString()
	if "TG_Open_Rectangular" in family:
		openings.append(i)
	if "TG_Open_Round" in family:
		openings_round.append(i)

shared_bp = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_SharedBasePoint).WhereElementIsNotElementType().ToElements()[0]
shared_bp_elev_parameter = shared_bp.LookupParameter("Elev")
shared_bp_elev = float(shared_bp_elev_parameter.AsValueString())

shared_bp_height = shared_bp.get_BoundingBox(None).Min.Z

TransactionManager.Instance.EnsureInTransaction(doc)

count = 0
for opening in openings:
	try:
		parameter = opening.LookupParameter(parameter_name)
		
		height = opening.Location.Point.Z
		
		#offset_parameter = opening.LookupParameter("Offset")
		#offset = offset_parameter.AsValueString()
		
		elevation = round(((height - shared_bp_height) * 30.48 + 0.3) / 100, digits)
		
		parameter.Set(str(elevation))
		
		#offset_parameter.Set(0)
		
		count += 1
	except:
		pass
for opening in openings_round:
	try:
		parameter = opening.LookupParameter(parameter_2_name)
		
		if bottom:
			height = opening.Location.Point.Z
		else:
			diameter_parameter = opening.Symbol.LookupParameter("Diameter of Sleeve")
			diameter = diameter_parameter.AsDouble()
			height = opening.Location.Point.Z + diameter / 2
		
		#offset_parameter = opening.LookupParameter("Offset")
		#offset = offset_parameter.AsValueString()
		
		elevation = round(((height - shared_bp_height) * 30.48) / 100, digits)
		
		parameter.Set(str(elevation))
		
		#offset_parameter.Set(0)
		
		count += 1
	except:
		pass

if shared_bp_height == shared_bp_elev:
	shared_bp_error = ""
else: 
	shared_bp_error = "\nSurvey point: internal height is not the same as elevation!"

"""
loc = XYZ(0,0,0)
f = openings[0].Symbol
a = doc.Create.NewFamilyInstance(loc, f, Structure.StructuralType.NonStructural)
"""

TransactionManager.Instance.TransactionTaskDone()

OUT = "Parameter set in " + str(count) + " instances" + shared_bp_error

"""
1. Выбор элементов категории "Generic Model".
2. Фильтрация по имени семейства "TG_Open_Rectangular" или "TG_Open_Round".
3. Выбор Shared Base Point проекта и его параметра Elev.
4. Для всех TG_Open_Rectangular параметр U.K. принимает значение возвышения над Shared Base Point в метрах.
	* Геометрия семейства на 0.3 см ниже чем его расчетный U.K.
5. Для всех TG_Open_Round параметр C.L. принимает значение возвышения над Shared Base Point в метрах.
	* Геометрия семейства на радиус ниже чем его расчетный C.L.
6. Проверка на одной ли высоте фактическая высота Shared Base Point и его Elev.
"""</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="619e9601-1d0f-4fd7-a071-6e99159e97e3" type="CoreNodeModels.Watch" nickname="Result" x="998.273256261106" y="342.221970079425" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Input.StringInput guid="c4684bc1-9fbb-400e-93b6-70552f02b1ca" type="CoreNodeModels.Input.StringInput" nickname="Parameter Name" x="442.389322698463" y="371.104981843179" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <System.String>U.K.</System.String>
      <System.String value="U.K." />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.DoubleSlider guid="3637d911-d7a9-4705-92bb-a1ff43adad19" type="CoreNodeModels.Input.DoubleSlider" nickname="Digits After Point" x="260.784805173011" y="312.817735224725" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>3</System.Double>
      <Range min="0" max="5" step="1" />
    </CoreNodeModels.Input.DoubleSlider>
    <CoreNodeModels.Input.BoolSelector guid="1daa66f1-c0ba-4571-ae03-b4b5c5a13e2d" type="CoreNodeModels.Input.BoolSelector" nickname="Round Openings: To The Bottom" x="347.718506906953" y="488.06202443355" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <CoreNodeModels.Input.StringInput guid="9bc8ca74-030f-4407-9ef3-829b66b88221" type="CoreNodeModels.Input.StringInput" nickname="Parameter Name" x="442.389322698463" y="429.752848904649" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <System.String>C.L.</System.String>
      <System.String value="C.L." />
    </CoreNodeModels.Input.StringInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c95d741a-105e-4832-9740-9cbe583c9238" start_index="0" end="619e9601-1d0f-4fd7-a071-6e99159e97e3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4684bc1-9fbb-400e-93b6-70552f02b1ca" start_index="0" end="c95d741a-105e-4832-9740-9cbe583c9238" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3637d911-d7a9-4705-92bb-a1ff43adad19" start_index="0" end="c95d741a-105e-4832-9740-9cbe583c9238" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1daa66f1-c0ba-4571-ae03-b4b5c5a13e2d" start_index="0" end="c95d741a-105e-4832-9740-9cbe583c9238" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9bc8ca74-030f-4407-9ef3-829b66b88221" start_index="0" end="c95d741a-105e-4832-9740-9cbe583c9238" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>